import {
  Role,
  LoaiDanhGia,
  PhamViApDung,
  TrangThaiBieuMau,
  type PhongBan,
  type User,
  type BieuMau,
  type CauHoi,
  type KyDanhGia,
  type DanhGia,
  type CauTraLoi,
} from "@/types/schema";

export const phongBans: PhongBan[] = [
  {
    id: "pb1",
    tenPhongBan: "Phòng Kỹ thuật",
    moTa: "Phòng phát triển sản phẩm và công nghệ",
    truongPhongId: "tp1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "pb2",
    tenPhongBan: "Phòng Kinh doanh",
    moTa: "Phòng bán hàng và chăm sóc khách hàng",
    truongPhongId: "tp2",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "pb3",
    tenPhongBan: "Phòng Nhân sự",
    moTa: "Phòng quản lý nguồn nhân lực",
    truongPhongId: "tp3",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "pb4",
    tenPhongBan: "Phòng Tài chính - Kế toán",
    moTa: "Phòng quản lý tài chính và kế toán",
    truongPhongId: "tp4",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "pb5",
    tenPhongBan: "Phòng Marketing",
    moTa: "Phòng marketing và truyền thông",
    truongPhongId: "tp5",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const users: User[] = [
  {
    id: "admin1",
    maNhanVien: "ADMIN001",
    hoTen: "Nguyễn Văn Admin",
    email: "admin@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.admin,
    phongBanId: "pb3",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "tp1",
    maNhanVien: "TP001",
    hoTen: "Trần Văn Kỹ Thuật",
    email: "tp.kythuat@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.truong_phong,
    phongBanId: "pb1",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "tp2",
    maNhanVien: "TP002",
    hoTen: "Lê Thị Kinh Doanh",
    email: "tp.kinhdoanh@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.truong_phong,
    phongBanId: "pb2",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "tp3",
    maNhanVien: "TP003",
    hoTen: "Phạm Văn Nhân Sự",
    email: "tp.nhansu@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.truong_phong,
    phongBanId: "pb3",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "tp4",
    maNhanVien: "TP004",
    hoTen: "Hoàng Thị Tài Chính",
    email: "tp.taichinh@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.truong_phong,
    phongBanId: "pb4",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "tp5",
    maNhanVien: "TP005",
    hoTen: "Vũ Văn Marketing",
    email: "tp.marketing@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.truong_phong,
    phongBanId: "pb5",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv1",
    maNhanVien: "NV001",
    hoTen: "Nguyễn Văn A",
    email: "nv001@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb1",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv2",
    maNhanVien: "NV002",
    hoTen: "Trần Thị B",
    email: "nv002@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb1",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv3",
    maNhanVien: "NV003",
    hoTen: "Lê Văn C",
    email: "nv003@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb1",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv4",
    maNhanVien: "NV004",
    hoTen: "Phạm Thị D",
    email: "nv004@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb1",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv5",
    maNhanVien: "NV005",
    hoTen: "Hoàng Văn E",
    email: "nv005@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb2",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv6",
    maNhanVien: "NV006",
    hoTen: "Vũ Thị F",
    email: "nv006@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb2",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv7",
    maNhanVien: "NV007",
    hoTen: "Đỗ Văn G",
    email: "nv007@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb2",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv8",
    maNhanVien: "NV008",
    hoTen: "Bùi Thị H",
    email: "nv008@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb2",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv9",
    maNhanVien: "NV009",
    hoTen: "Đinh Văn I",
    email: "nv009@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb3",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv10",
    maNhanVien: "NV010",
    hoTen: "Dương Thị K",
    email: "nv010@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb3",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv11",
    maNhanVien: "NV011",
    hoTen: "Cao Văn L",
    email: "nv011@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb3",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv12",
    maNhanVien: "NV012",
    hoTen: "Lý Thị M",
    email: "nv012@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb3",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv13",
    maNhanVien: "NV013",
    hoTen: "Mai Văn N",
    email: "nv013@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb4",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv14",
    maNhanVien: "NV014",
    hoTen: "Tô Thị O",
    email: "nv014@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb4",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv15",
    maNhanVien: "NV015",
    hoTen: "Hồ Văn P",
    email: "nv015@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb4",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv16",
    maNhanVien: "NV016",
    hoTen: "Phan Thị Q",
    email: "nv016@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb4",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv17",
    maNhanVien: "NV017",
    hoTen: "Đặng Văn R",
    email: "nv017@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb5",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv18",
    maNhanVien: "NV018",
    hoTen: "Tạ Thị S",
    email: "nv018@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb5",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv19",
    maNhanVien: "NV019",
    hoTen: "Ông Văn T",
    email: "nv019@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb5",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "nv20",
    maNhanVien: "NV020",
    hoTen: "Lâm Thị U",
    email: "nv020@company.com",
    matKhau: "$2a$10$YourHashedPasswordHere",
    role: Role.nhan_vien,
    phongBanId: "pb5",
    daDangKy: true,
    trangThaiKH: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const kyDanhGias: KyDanhGia[] = [
  {
    id: "ky1",
    tenKy: "Đánh giá Quý 4/2024",
    moTa: "Kỳ đánh giá quý 4 năm 2024",
    ngayBatDau: new Date("2024-10-01"),
    ngayKetThuc: new Date("2024-12-31"),
    dangMo: true,
    createdAt: new Date("2024-09-15"),
    updatedAt: new Date("2024-09-15"),
  },
  {
    id: "ky2",
    tenKy: "Đánh giá Quý 3/2024",
    moTa: "Kỳ đánh giá quý 3 năm 2024",
    ngayBatDau: new Date("2024-07-01"),
    ngayKetThuc: new Date("2024-09-30"),
    dangMo: false,
    createdAt: new Date("2024-06-15"),
    updatedAt: new Date("2024-10-01"),
  },
];

export const bieuMaus: BieuMau[] = [
  {
    id: "bm1",
    tenBieuMau: "Đánh giá năng lực lãnh đạo",
    loaiDanhGia: LoaiDanhGia.LANH_DAO,
    phamViApDung: PhamViApDung.TOAN_CONG_TY,
    trangThai: TrangThaiBieuMau.KICH_HOAT,
    moTa: "Biểu mẫu đánh giá năng lực lãnh đạo áp dụng cho toàn công ty",
    nguoiTaoId: "admin1",
    ngayPhatHanh: new Date("2024-09-01"),
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-09-01"),
  },
  {
    id: "bm2",
    tenBieuMau: "Đánh giá năng lực nhân viên",
    loaiDanhGia: LoaiDanhGia.NHAN_VIEN,
    phamViApDung: PhamViApDung.TOAN_CONG_TY,
    trangThai: TrangThaiBieuMau.KICH_HOAT,
    moTa: "Biểu mẫu đánh giá năng lực nhân viên áp dụng cho toàn công ty",
    nguoiTaoId: "admin1",
    ngayPhatHanh: new Date("2024-09-01"),
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-09-01"),
  },
];

export const cauHois: CauHoi[] = [
  {
    id: "ch1",
    bieuMauId: "bm1",
    noiDung: "Khả năng lãnh đạo và truyền cảm hứng cho đội ngũ",
    thuTu: 1,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: "ch2",
    bieuMauId: "bm1",
    noiDung: "Khả năng ra quyết định và giải quyết vấn đề",
    thuTu: 2,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: "ch3",
    bieuMauId: "bm1",
    noiDung: "Kỹ năng giao tiếp và lắng nghe",
    thuTu: 3,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: "ch4",
    bieuMauId: "bm1",
    noiDung: "Khả năng phát triển và đào tạo nhân viên",
    thuTu: 4,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: "ch5",
    bieuMauId: "bm1",
    noiDung: "Tầm nhìn chiến lược và định hướng phát triển",
    thuTu: 5,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: "ch6",
    bieuMauId: "bm2",
    noiDung: "Chất lượng công việc và độ chính xác",
    thuTu: 1,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: "ch7",
    bieuMauId: "bm2",
    noiDung: "Tinh thần trách nhiệm và cam kết công việc",
    thuTu: 2,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: "ch8",
    bieuMauId: "bm2",
    noiDung: "Khả năng làm việc nhóm và hợp tác",
    thuTu: 3,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: "ch9",
    bieuMauId: "bm2",
    noiDung: "Sáng tạo và đổi mới trong công việc",
    thuTu: 4,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: "ch10",
    bieuMauId: "bm2",
    noiDung: "Khả năng học hỏi và phát triển bản thân",
    thuTu: 5,
    diemToiDa: 5,
    batBuoc: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-08-15"),
  },
];

export const danhGias: DanhGia[] = [];

export const cauTraLois: CauTraLoi[] = [];

