// Generated from Excel file: XLKL - 2025.xlsx
// Sheet: Tổng hợp điểm phạt
// Data from row 8 to 250, header at row 7

export interface TongHopDiemPhat {
  tt: number | null;
  họVàTên: string | null;
  mãNhânViên: string | null;
  bộPhận: string | null;
  tháng2: number | null;
  tháng3: number | null;
  tháng4: number | null;
  tháng5: number | null;
  tháng6: number | null;
  tháng7: number | null;
  tháng8: number | null;
  tháng9: number | null;
  tháng10: number | null;
  tháng11: number | null;
  tổng: number | null;
}

export const tongHopDiemPhats: TongHopDiemPhat[] = [
  {
    tt: 1,
    họVàTên: "Lê Văn Chính",
    mãNhânViên: "NV2579",
    bộPhận: "NV Tổ bảo vệ Phòng TC",
    tháng2: 15,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 2,
    họVàTên: "Hoàng Ngọc Dương",
    mãNhânViên: "NV4119",
    bộPhận: "NV Thủ kho Phòng Kế toán",
    tháng2: 20,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 3,
    họVàTên: "Đỗ Đức Nam",
    mãNhânViên: "NV3323",
    bộPhận: "NV QC Ban kiểm soát",
    tháng2: 10,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 4,
    họVàTên: "Viên Đình Khang",
    mãNhânViên: "NV1871",
    bộPhận: "Lái xe nâng - Tổ PVXH",
    tháng2: 18,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 18,
  },
  {
    tt: 5,
    họVàTên: "Nguyễn Xuân Thuỷ",
    mãNhânViên: "NV5019",
    bộPhận: "NV lái xe mỏ - Phòng khai thác",
    tháng2: 20,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 6,
    họVàTên: "Lê Bá Cẩn",
    mãNhânViên: "NV5273",
    bộPhận: "NV lái xe mỏ - Phòng khai thác",
    tháng2: 5,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 7,
    họVàTên: "Nguyễn Duy Dương",
    mãNhânViên: "NV4640",
    bộPhận: "CN Dây chuyền - BP nhiên liệu và gia công bán thành phẩm",
    tháng2: 20,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 8,
    họVàTên: "Phạm Văn Sơn",
    mãNhânViên: "NV4187",
    bộPhận: "Công nhân Lái xe nâng - DC5 - PXSX2",
    tháng2: 30,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 30,
  },
  {
    tt: 9,
    họVàTên: "Nguyễn Huy Toàn",
    mãNhânViên: "NV0695",
    bộPhận: "NV Thủ kho Phòng Kế toán",
    tháng2: null,
    tháng3: 8,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 8,
  },
  {
    tt: 10,
    họVàTên: "Lê Đình Tuấn",
    mãNhânViên: "NV2486",
    bộPhận: "NV Tổ bảo vệ Phòng TC",
    tháng2: null,
    tháng3: 5,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 13,
    tháng10: null,
    tháng11: null,
    tổng: 18,
  },
  {
    tt: 11,
    họVàTên: "Nguyễn Thị Bích Hường",
    mãNhânViên: "NV0041",
    bộPhận: "GĐ ban kinh doanh",
    tháng2: null,
    tháng3: 2,
    tháng4: 3,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 12,
    họVàTên: "Đỗ Thị Hằng",
    mãNhânViên: "NV1278",
    bộPhận: "Nhân viên điều phối vùng 8+9 - Ban kinh doanh",
    tháng2: null,
    tháng3: 5,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 13,
    họVàTên: "Nguyễn Văn Tuấn",
    mãNhânViên: "NV5394",
    bộPhận: "NV lái xe mỏ - Phòng khai thác",
    tháng2: null,
    tháng3: 15,
    tháng4: 5,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 14,
    họVàTên: "Lê Bá Triệu",
    mãNhânViên: "NV2213",
    bộPhận: "Lái xe nâng - Tổ PVXH",
    tháng2: null,
    tháng3: 15,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 15,
    họVàTên: "Hoàng Huy Tuấn",
    mãNhânViên: "NV0756",
    bộPhận: "Tổ phó hậu cần nội vụ , PXSX1",
    tháng2: null,
    tháng3: 5,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 16,
    họVàTên: "Nguyễn Viết Thanh",
    mãNhânViên: "NV0131",
    bộPhận: "NT xúc lật",
    tháng2: null,
    tháng3: 5,
    tháng4: 3,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 10,
    tháng10: 20,
    tháng11: null,
    tổng: 38,
  },
  {
    tt: 17,
    họVàTên: "Nguyễn Khắc Thành",
    mãNhânViên: "NV0135",
    bộPhận: "NT xúc lật",
    tháng2: null,
    tháng3: 5,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 10,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 18,
    họVàTên: "Nguyễn Khắc Thảo",
    mãNhânViên: "NV1618",
    bộPhận: "NT xúc lật",
    tháng2: null,
    tháng3: 5,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 10,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 19,
    họVàTên: "Lê Duy Hùng",
    mãNhânViên: "NV0659",
    bộPhận: "Tổ trưởng DC gia công ca A - BP DC gia công và lò nung DC5 - PXSX2",
    tháng2: null,
    tháng3: 2,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 20,
    họVàTên: "Nguyễn Thái Thuận",
    mãNhânViên: "NV0486",
    bộPhận: "Vận hành máy đóng bao ca 1A DC6 PXSX2",
    tháng2: null,
    tháng3: 5,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 21,
    họVàTên: "Nguyễn Trung Kiên",
    mãNhânViên: "NV4623",
    bộPhận: "Quản lý dây chuyền mài PXSX2",
    tháng2: null,
    tháng3: 3,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 22,
    họVàTên: "Trần Thanh Hải",
    mãNhânViên: "NV3449",
    bộPhận: "Tổ trưởng mài ca B PXSX2",
    tháng2: null,
    tháng3: 6,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 23,
    họVàTên: "Văn Tiến Đức",
    mãNhânViên: "NV4557",
    bộPhận: "Công nhân vận hành bể nước thải PXSX2",
    tháng2: null,
    tháng3: 20,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 24,
    họVàTên: "Lưu Đăng Khoa",
    mãNhânViên: "NV5216",
    bộPhận: "Nhân viên test mẫu, BP Công nghệ PXSX2",
    tháng2: null,
    tháng3: 20,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 25,
    họVàTên: "Nguyễn Sỹ Tư",
    mãNhânViên: "NV3086",
    bộPhận: "Nhân viên test mẫu, BP Công nghệ PXSX2",
    tháng2: null,
    tháng3: 7,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 7,
  },
  {
    tt: 26,
    họVàTên: "Vũ Đình Hoàng",
    mãNhânViên: "NV0215",
    bộPhận: "CBKT, BP Công nghệ PXSX2",
    tháng2: null,
    tháng3: 3,
    tháng4: 3,
    tháng5: 5,
    tháng6: null,
    tháng7: 5,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 21,
  },
  {
    tt: 27,
    họVàTên: "Nguyễn Văn Dương",
    mãNhânViên: "NV0005",
    bộPhận: "PGĐ - Ban kinh doanh",
    tháng2: null,
    tháng3: null,
    tháng4: 2,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 28,
    họVàTên: "Lê Thị Thanh Thuý",
    mãNhânViên: "NV4081",
    bộPhận: "NV - Phòng kế toán",
    tháng2: null,
    tháng3: null,
    tháng4: 8,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 8,
  },
  {
    tt: 29,
    họVàTên: "Trần Thị Hương",
    mãNhânViên: "NV0027",
    bộPhận: "Ban kinh doanh",
    tháng2: null,
    tháng3: null,
    tháng4: 3,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 30,
    họVàTên: "Nguyễn Thị Biên",
    mãNhânViên: "NV0036",
    bộPhận: "Nhân viên hỗ trợ thị trường - Ban kinh doanh",
    tháng2: null,
    tháng3: null,
    tháng4: 39,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 39,
  },
  {
    tt: 31,
    họVàTên: "Nguyễn Thị Hà",
    mãNhânViên: "NV2352",
    bộPhận: "Nhân viên hỗ trợ thị trường - Ban kinh doanh",
    tháng2: null,
    tháng3: null,
    tháng4: 3,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 32,
    họVàTên: "Lê Hữu Mạnh",
    mãNhânViên: "NV0861",
    bộPhận: "Nhân viên hỗ trợ thị trường - Ban kinh doanh",
    tháng2: null,
    tháng3: null,
    tháng4: 3,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 33,
    họVàTên: "Lê Tuấn Anh",
    mãNhânViên: "NV0058",
    bộPhận: "Phó phòng sản xuất - PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: 5,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 34,
    họVàTên: "Hoàng Minh Hà",
    mãNhânViên: "NV0450",
    bộPhận: "Phó giám đốc PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: 5,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 35,
    họVàTên: "Nguyễn Văn Thanh ",
    mãNhânViên: "NV0765",
    bộPhận: "Trưởng phòng sản xuất PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: 5,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 36,
    họVàTên: "Lê Khắc Bình",
    mãNhânViên: "NV0771",
    bộPhận: "Giám đốc PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: 5,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 37,
    họVàTên: "Nguyễn Phú Thêm",
    mãNhânViên: "NV0207",
    bộPhận: "Tổ trưởng lò nung PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: 10,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 38,
    họVàTên: "Trần Văn Hùng",
    mãNhânViên: "NV0223",
    bộPhận: "Phó bộ phận -Phụ trách đóng hộp PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: 15,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 2,
    tháng11: null,
    tổng: 17,
  },
  {
    tt: 39,
    họVàTên: "Vương Huy Trường",
    mãNhânViên: "NV0264",
    bộPhận: "Tổ trưởng ca B Bộ phận đóng hộp PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: 10,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 40,
    họVàTên: "Đoàn Ngọc Thanh",
    mãNhânViên: "NV0269",
    bộPhận: "Tổ trưởng ca A Bộ phận đóng hộp PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: 10,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 41,
    họVàTên: "Nguyễn Thị Phương",
    mãNhânViên: "NV5326",
    bộPhận: "Công nhân bốc lai DC1 PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: 12,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 12,
  },
  {
    tt: 42,
    họVàTên: "Lưu Đăng Khoa",
    mãNhânViên: "NV5216",
    bộPhận: "Bộ phận công nghệ",
    tháng2: null,
    tháng3: null,
    tháng4: 20,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 43,
    họVàTên: "Nguyễn Sỹ Tư",
    mãNhânViên: "NV3086",
    bộPhận: "Bộ phận công nghệ",
    tháng2: null,
    tháng3: null,
    tháng4: 7,
    tháng5: 11,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 18,
  },
  {
    tt: 44,
    họVàTên: "Nguyễn Thế Tài",
    mãNhânViên: "NV0538",
    bộPhận: "Bộ phận nguyên liệu và gia công",
    tháng2: null,
    tháng3: null,
    tháng4: 5,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 45,
    họVàTên: "Đỗ Như Giang",
    mãNhânViên: "NV1903",
    bộPhận: "Bộ phận nguyên liệu và gia công",
    tháng2: null,
    tháng3: null,
    tháng4: 5,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 46,
    họVàTên: "Phạm Duy Thiết",
    mãNhânViên: "NV0651",
    bộPhận: "Bộ phận nguyên liệu và gia công",
    tháng2: null,
    tháng3: null,
    tháng4: 2,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 47,
    họVàTên: "Lê Xuân Cảnh",
    mãNhânViên: "NV0161",
    bộPhận: "Bộ phận KCS - Ban thanh tra kiểm soát",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 11,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 11,
  },
  {
    tt: 48,
    họVàTên: "Nguyễn Đình Toàn",
    mãNhânViên: "NV1435",
    bộPhận: "Bộ phận KCS - Ban thanh tra kiểm soát",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 23,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 23,
  },
  {
    tt: 49,
    họVàTên: "Nguyễn Mạnh Uyên",
    mãNhânViên: "NV3214",
    bộPhận: "Trưởng bộ phận kế hoạch SX - BKD",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 5,
    tháng6: null,
    tháng7: 6,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 11,
  },
  {
    tt: 50,
    họVàTên: "Vũ Xuân Tuấn",
    mãNhânViên: "NV1118",
    bộPhận: "TGĐ",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 3,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 51,
    họVàTên: "Lê Quang Trung",
    mãNhânViên: "NV0093",
    bộPhận: "Phó TGĐ - Phụ trách Phòng Tổ chức",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 52,
    họVàTên: "Đỗ Xuân Chinh",
    mãNhânViên: "NV4890",
    bộPhận: "Lái xe - Phòng khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 16,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 16,
  },
  {
    tt: 53,
    họVàTên: "Lê Khả Hoàng",
    mãNhânViên: "NV0157",
    bộPhận: "Nhóm trưởng - Bộ phận KCS - Ban thanh tra kiểm soát",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 5,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 54,
    họVàTên: "Nguyễn Thái Sỹ",
    mãNhânViên: "NV0162",
    bộPhận: "Tổ trưởng - Bộ phận KCS - Ban thanh tra kiểm soát",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 3,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 55,
    họVàTên: "Lê Đức Kiệm",
    mãNhânViên: "NV0716",
    bộPhận: "Lái máy xúc đào - Phòng khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 3,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 56,
    họVàTên: "Bùi Sỹ Quang",
    mãNhânViên: "NV0133",
    bộPhận: "TBP nghiền sấy phun - PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 22,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 22,
  },
  {
    tt: 57,
    họVàTên: "Phan Văn Thắng",
    mãNhânViên: "NV0275",
    bộPhận: "Phó bộ phận nhiên liệu và gia công bán thành phẩm",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 8,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 13,
  },
  {
    tt: 58,
    họVàTên: "Lê Thị Bình",
    mãNhânViên: "NV0132",
    bộPhận: "Bộ phận nung và hoàn thiện sản phẩm PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 19,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 19,
  },
  {
    tt: 59,
    họVàTên: "Phạm Văn Thùy",
    mãNhânViên: "NV2737",
    bộPhận: "Nhân viên test mẫu - Bộ phận công nghệ PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 14,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 14,
  },
  {
    tt: 60,
    họVàTên: "Nguyễn Trường Giang",
    mãNhânViên: "NV2660",
    bộPhận: "Vận hành máy in KTS PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 3,
    tháng6: null,
    tháng7: 18,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 21,
  },
  {
    tt: 61,
    họVàTên: "Cao Văn Nhân",
    mãNhânViên: "NV2764",
    bộPhận: "NV kiểm soát công nghệ PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 62,
    họVàTên: "Mai Cát Vượng",
    mãNhânViên: "NV0425",
    bộPhận: "NV kiểm soát công nghệ PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 63,
    họVàTên: "Lê Duy Nam",
    mãNhânViên: "NV0068",
    bộPhận: "NV kiểm soát công nghệ PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 64,
    họVàTên: "Mai Trọng Ninh",
    mãNhânViên: "NV1108",
    bộPhận: "Công nhận vận hành sấy phun PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 3,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 65,
    họVàTên: "Đỗ Ngọc Vui",
    mãNhânViên: "NV1697",
    bộPhận: "Công nhận vận hành sấy phun PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 3,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 66,
    họVàTên: "Nguyễn Trọng Luật",
    mãNhânViên: "NV0286",
    bộPhận: "Tổ trưởng sấy phun PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 67,
    họVàTên: "Trịnh Xuân Mong",
    mãNhânViên: "NV0293",
    bộPhận: "Tổ trưởng sấy phun PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 68,
    họVàTên: "Nguyễn Hoàng Dũng",
    mãNhânViên: "NV0574",
    bộPhận: "Phó bộ phận dây chuyền PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: 5,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 7,
  },
  {
    tt: 69,
    họVàTên: "Trương Văn Thắng",
    mãNhânViên: "NV0195",
    bộPhận: "Phó bộ phận dây chuyền PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 70,
    họVàTên: "Bùi Khắc Toàn",
    mãNhânViên: "NV2085",
    bộPhận: "Giám sát cân định lượng PXSX",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 71,
    họVàTên: "Nguyễn Đức Thanh",
    mãNhânViên: "NV5347",
    bộPhận: "Công nhân - Bộ phận Trạm than và Lò nung PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 5,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 72,
    họVàTên: "Nguyễn Kiên Cường",
    mãNhânViên: "NV2776",
    bộPhận: "Công nhân - Bộ phận Mài và Đóng hộp PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 5,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 73,
    họVàTên: "Trương Văn Nam",
    mãNhânViên: "NV3775",
    bộPhận: "Công nhân - Bộ phận Mài và Đóng hộp PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 5,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 74,
    họVàTên: "Lường Văn Tùng",
    mãNhânViên: "NV4564",
    bộPhận: "Công nhân - Bộ phận Mài và Đóng hộp PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 5,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 75,
    họVàTên: "Vũ Đình Lương",
    mãNhânViên: "NV5045",
    bộPhận: "Công nhân - Bộ phận Mài và Đóng hộp PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 5,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 76,
    họVàTên: "Lê Công Dũng",
    mãNhânViên: "NV3688",
    bộPhận: "Công nhân - Bộ phận Mài và Đóng hộp PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 5,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 77,
    họVàTên: "Tống Văn Tỵ",
    mãNhânViên: "NV0576",
    bộPhận: "Tổ trưởng - Bộ phận Mài và Đóng hộp PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 18,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 18,
  },
  {
    tt: 78,
    họVàTên: "Lê Xuân Long",
    mãNhânViên: "NV0087",
    bộPhận: "Phó phòng Kỹ thuật - Phụ trách mài PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 79,
    họVàTên: "Nguyễn Trung Kiên",
    mãNhânViên: "NV4623",
    bộPhận: "Phó Bp Mài - PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 2,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 80,
    họVàTên: "Hoàng Đình Bảy",
    mãNhânViên: "NV3966",
    bộPhận: "Tổ phó mài ca B PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 5,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 81,
    họVàTên: "Trần Quốc Tuấn",
    mãNhânViên: "NV0600",
    bộPhận: "Giám đốc PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: 3,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 82,
    họVàTên: "Mai Văn Thanh",
    mãNhânViên: "NV0092",
    bộPhận: "CV - Cán bộ kỹ thuật - Ban đầu tư và khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 10,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 83,
    họVàTên: "Nguyễn Văn Tuấn",
    mãNhânViên: "NV0096",
    bộPhận: "CV - Cán bộ kỹ thuật - Ban đầu tư và khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 5,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 84,
    họVàTên: "Đỗ Đức Tùng",
    mãNhânViên: "NV0340",
    bộPhận: "TBP kho Đông Văn",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 2,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 85,
    họVàTên: "Hoàng Đức Bình",
    mãNhânViên: "NV0736",
    bộPhận: "Nhân viên sơ chế - Tổ phục vụ xuất hàng",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 12,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 12,
  },
  {
    tt: 86,
    họVàTên: "Nguyễn Bá Dũng",
    mãNhânViên: "NV0389",
    bộPhận: "Nhân viên lái xe nâng - Tổ phục vụ xuất hàng",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 12,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 12,
  },
  {
    tt: 87,
    họVàTên: "Nguyễn Văn Tâm",
    mãNhânViên: "NV1309",
    bộPhận: "Nhân viên sơ chế - Tổ phục vụ xuất hàng",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 6,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 88,
    họVàTên: "Nguyễn Văn Dũng",
    mãNhânViên: "NV0403",
    bộPhận: "Nhân viên lái xe con - Phòng tổ chức hành chính",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 25,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 25,
  },
  {
    tt: 89,
    họVàTên: "Nguyễn Đăng Thiên",
    mãNhânViên: "NV2434",
    bộPhận: "Nhân viên thiết kế - Ban kinh doanh",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 11,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 11,
  },
  {
    tt: 90,
    họVàTên: "Lê Bá Cần",
    mãNhânViên: "NV5273",
    bộPhận: "Lái xe- Ban đầu tư và khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 6,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 91,
    họVàTên: "Lê Văn Tuấn Anh",
    mãNhânViên: "NV5534",
    bộPhận: "Nhân viên lái xe nâng - Tổ phục vụ xuất hàng",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 15,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 92,
    họVàTên: "Trần Văn Kỳ",
    mãNhânViên: "NV0086",
    bộPhận: "Thủ kho - Phòng kế Toán",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 5,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 93,
    họVàTên: "Mai Văn Tới",
    mãNhânViên: "NV4627",
    bộPhận: "Tổ trưởng Bảo dưỡng HC - Bộ phận mài PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 6,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 94,
    họVàTên: "Bùi Văn Chinh",
    mãNhânViên: "NV4794",
    bộPhận: "Tổ trưởng mài ca B - PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 6,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 15,
    tháng11: null,
    tổng: 21,
  },
  {
    tt: 95,
    họVàTên: "Lê Ngọc Khánh",
    mãNhânViên: "NV0257",
    bộPhận: "Tổ trưởng mài ca A - PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 6,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 96,
    họVàTên: "Lê Đình Toàn",
    mãNhânViên: "NV0454",
    bộPhận: "Phó bộ phận mài PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 10,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 97,
    họVàTên: "Đào Xuân Hùng",
    mãNhânViên: "NV0181",
    bộPhận: "VH máy ép PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 20,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 98,
    họVàTên: "Cao Văn Mùi",
    mãNhânViên: "NV0980",
    bộPhận: "Tổ trưởng ca A PXSX1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 14,
    tháng7: 11,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 25,
  },
  {
    tt: 99,
    họVàTên: "Nguyễn Duy Xuân",
    mãNhânViên: "NV1279",
    bộPhận: "VH máy mài cạnh - DC5 PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 5,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 100,
    họVàTên: "Nguyễn Trọng Tiến",
    mãNhânViên: "NV0243",
    bộPhận: "Công nhân VH DC5 PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 10,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 101,
    họVàTên: "Nguyễn Văn Cảnh",
    mãNhânViên: "NV0628",
    bộPhận: "Công nhân hoàn thiện Palet DC5 PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 10,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 102,
    họVàTên: "Vũ Xuân Lâm",
    mãNhânViên: "NV0205",
    bộPhận: "Công nhân vận hành lò xương DC5 PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 2,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 103,
    họVàTên: "Đỗ Văn Thắng",
    mãNhânViên: "NV3172",
    bộPhận: "Công nhân lò nung DC5 PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 10,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 104,
    họVàTên: "Phạm Đức Mạnh",
    mãNhânViên: "NV0603",
    bộPhận: "PBP Phụ trách NSP DC5,6 và dây chuyển gia công DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 2,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 105,
    họVàTên: "Lê Ngọc Hiếu",
    mãNhânViên: "NV0567",
    bộPhận: "Tổ trưởng ca A- Phụ trách DC gia công Dc6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 3,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 106,
    họVàTên: "Lê Xuân Bắc",
    mãNhânViên: "NV0575",
    bộPhận: "Công nhân VH máy ép DC6 PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 10,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 107,
    họVàTên: "Lê Viết Trung",
    mãNhânViên: "NV0430",
    bộPhận: "Phụ trách trạm than-lò nung và đóng hộp Dc6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 5,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 108,
    họVàTên: "Lê Văn Tuân",
    mãNhânViên: "NV1100",
    bộPhận: "NV Vận hành máy ép -DC5 PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 6,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 109,
    họVàTên: "Lê Văn Huy",
    mãNhânViên: "NV5167",
    bộPhận: "NV Vận hành máy in KTS -DC5 PXSX2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: 11,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 11,
  },
  {
    tt: 110,
    họVàTên: "Nguyễn Xuân Sơn",
    mãNhânViên: "NV3542",
    bộPhận: "Thủ kho công trình Quảng Thành - Ban đầu tư",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 15,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 111,
    họVàTên: "Trần Thị Hiền",
    mãNhânViên: "NV0824",
    bộPhận: "Thủ kho Đông Văn - Phòng kế toán",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 2,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: 8,
    tổng: 10,
  },
  {
    tt: 112,
    họVàTên: "Đỗ Đức Tùng",
    mãNhânViên: "NV0340",
    bộPhận: "Trưởng bộ phận kho Đông Văn - Ban đầu tư - khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 3,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 113,
    họVàTên: "Lê Hữu Phước",
    mãNhânViên: "NV4515",
    bộPhận: "Nhân viên lái xe - Ban đầu tư - khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 114,
    họVàTên: "Văn Doãn Hoa",
    mãNhânViên: "NV5515",
    bộPhận: "Nhân viên KCS - Tổ thanh tra sản xuất",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 15,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 115,
    họVàTên: "Nguyễn Hữu Chung",
    mãNhânViên: "NV3301",
    bộPhận: "Nhân viên bảo vệ - Ban thanh tra kiểm soát",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 13,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 13,
  },
  {
    tt: 116,
    họVàTên: "Phạm Văn Năm",
    mãNhânViên: "NV2749",
    bộPhận: "Nhân viên lái máy - Ban đầu tư - khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 117,
    họVàTên: "Nguyễn Trọng Bình",
    mãNhânViên: "NV0158",
    bộPhận: "Nhóm trưởng - Tổ thanh tra sản xuất",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 118,
    họVàTên: "Lê Văn Trường",
    mãNhânViên: "NV1612",
    bộPhận: "CBKT Mài - BP máy mài",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 15,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 119,
    họVàTên: "Nguyễn Văn Tưởng",
    mãNhânViên: "NV4752",
    bộPhận: "Công nhân lái xe nâng đi ca",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 6,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 120,
    họVàTên: "Vương Huy Tân",
    mãNhânViên: "NV5418",
    bộPhận: "Công nhân bao gói ca B ",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 6,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 121,
    họVàTên: "Vương Huy Phúc",
    mãNhânViên: "NV5419",
    bộPhận: "Công nhân bao gói ca B ",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 6,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 122,
    họVàTên: "Lê Vạn Tâm ",
    mãNhânViên: "NV3376",
    bộPhận: "Vận hành máy mài cạnh B",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 13,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 13,
  },
  {
    tt: 123,
    họVàTên: "Trịnh Tuấn Linh",
    mãNhânViên: "NV1200",
    bộPhận: "CN vận hành máy in KTS ca B",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 15,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 124,
    họVàTên: "Lê Văn Thuận",
    mãNhânViên: "NV0183",
    bộPhận: "Tổ trưởng dây chuyền ca B",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 10,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 126,
    họVàTên: "Nguyễn Xuân Dũng",
    mãNhânViên: "NV1263",
    bộPhận: "VH Máy in kỹ thuật số ca A",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 3,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 127,
    họVàTên: "Lê Tiến Đại",
    mãNhânViên: "NV0323",
    bộPhận: "VH Máy in kỹ thuật số ca A",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 3,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 128,
    họVàTên: "Đỗ Ngọc Vui",
    mãNhânViên: "NV1697",
    bộPhận: "Công nhân Nghiền sấy phun ca A",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 3,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 129,
    họVàTên: "Vương Huy Trường",
    mãNhânViên: "NV0264",
    bộPhận: "Tổ trưởng bao gói ca B",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 11,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 11,
  },
  {
    tt: 130,
    họVàTên: "Phạm Văn Chiến",
    mãNhânViên: "NV0617",
    bộPhận: "Tổ trưởng - Bộ phận nung và hoàn thiện sản phẩm DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 131,
    họVàTên: "Nguyễn Thương Huyền",
    mãNhânViên: "NV0606",
    bộPhận: "Tổ trưởng - Bộ phận nung và hoàn thiện sản phẩm DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 132,
    họVàTên: "Hoàng Văn Vũ",
    mãNhânViên: "NV0976",
    bộPhận: "Tổ trưởng cơ điện - Phòng kỹ thuật",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 3,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 133,
    họVàTên: "Lê Văn Đại",
    mãNhânViên: "NV0107",
    bộPhận: "Tổ phó cơ điện - Phòng kỹ thuật",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 134,
    họVàTên: "Lê Đức Dự",
    mãNhânViên: "NV0544",
    bộPhận: "Công nhân lái xe nâng ca A - Bộ phận nung và hoàn thiện sản phẩm DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 15,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 135,
    họVàTên: "Nguyễn Thương Huyền",
    mãNhânViên: "NV0606",
    bộPhận: "Tổ trưởng - Bộ phận nung và hoàn thiện sản phẩm DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 15,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 136,
    họVàTên: "Viên Trịnh Hà",
    mãNhânViên: "NV4587",
    bộPhận: "VH máy mài cạnh - BP máy mài DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 6,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 137,
    họVàTên: "Ngô Công Tám",
    mãNhânViên: "NV5496",
    bộPhận: "CN bao gói ca B -DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 14,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 14,
  },
  {
    tt: 138,
    họVàTên: "Đỗ Văn Thành",
    mãNhânViên: "NV5560",
    bộPhận: "CN bao gói ca B -DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 14,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 14,
  },
  {
    tt: 139,
    họVàTên: "Nguyễn Viết Linh",
    mãNhânViên: "NV1892",
    bộPhận: "Tổ trưởng bao gói ca B",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 140,
    họVàTên: "Trương Quốc Thịnh",
    mãNhânViên: "NV3011",
    bộPhận: "CN vận hành máy in KTS - DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 141,
    họVàTên: "Phạm Duy Thiết",
    mãNhânViên: "NV0651",
    bộPhận: "Tổ trưởng dây chuyền ca B",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 142,
    họVàTên: "Phùng Văn Dũng",
    mãNhânViên: "NV0714",
    bộPhận: "Lái xúc lật",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 23,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 23,
  },
  {
    tt: 143,
    họVàTên: "Nguyễn Thế Tài",
    mãNhânViên: "NV1903",
    bộPhận: "Nhóm trưởng - Bộ phận Nghiền, sấy phun",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 11,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 11,
  },
  {
    tt: 144,
    họVàTên: "Lê Nhữ Đạt",
    mãNhânViên: "NV3296",
    bộPhận: "Công nhân lò nung ca A",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 20,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 145,
    họVàTên: "Lê Ngọc Hiếu",
    mãNhânViên: "NV0567",
    bộPhận: "Tổ trưởng dây chuyền ca A - DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 146,
    họVàTên: "Vũ Đức Cường",
    mãNhânViên: "NV0768",
    bộPhận: "Nhân viên thiết kế - Bộ phận công nghệ",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 10,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 147,
    họVàTên: "Phạm Đức Mạnh",
    mãNhânViên: "NV0603",
    bộPhận: "Phó bộ phận Gia công nguyên liệu",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 148,
    họVàTên: "Nguyễn Đức Toán",
    mãNhânViên: "NV0588",
    bộPhận: "Tổ trưởng dây chuyền ca A - DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 149,
    họVàTên: "Lê Hữu Việt",
    mãNhânViên: "NV3245",
    bộPhận: "Công nhân vận hành máy in kỹ thuật số ca A",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 10,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 150,
    họVàTên: "Lê Kiên Quyết",
    mãNhânViên: "NV5628",
    bộPhận: "Công nhân bao gói ca A - DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 151,
    họVàTên: "Đỗ Xuân Quyết",
    mãNhânViên: "NV5563",
    bộPhận: "Công nhân bao gói ca A - DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 152,
    họVàTên: "Lê Hữu Quyền",
    mãNhânViên: "NV4046",
    bộPhận: "Công nhân nghiền sấy phun - DC5 (Điều động hỗ trợ tạm thời sang bao gói)",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 153,
    họVàTên: "Phạm Văn Sơn",
    mãNhânViên: "NV4187",
    bộPhận: "Công nhân lái xe nâng đi ca",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 154,
    họVàTên: "Lê Văn Kiên",
    mãNhânViên: "NV4424",
    bộPhận: "Công nhân bao gói ca B - DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 155,
    họVàTên: "Bùi Sĩ Trung",
    mãNhânViên: "NV5543",
    bộPhận: "Công nhân bao gói ca A - DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 156,
    họVàTên: "Nguyễn Thị Hoài Thu",
    mãNhânViên: "NV0621",
    bộPhận: "Công nhân bao gói ca A - DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 157,
    họVàTên: "Nguyễn Sĩ Sáu",
    mãNhânViên: "NV5222",
    bộPhận: "Công nhân bao gói ca A - DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: 5,
    tháng8: null,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 158,
    họVàTên: "Hoàng Phú Đạt",
    mãNhânViên: "NV5157",
    bộPhận: "GĐ vùng 9",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 159,
    họVàTên: "Le Thị Nhung",
    mãNhânViên: "NV0081",
    bộPhận: "NV hỗ trợ thị trường BKD",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 160,
    họVàTên: "Cao Văn Tân",
    mãNhânViên: "NV0480",
    bộPhận: "Công nhân VH máy ép - Bộ phận dây chuyền gia công và Lò nung",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 15,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 161,
    họVàTên: "Trương Quốc Cường",
    mãNhânViên: "NV1261",
    bộPhận: "Công nhân VH máy ép - Bộ phận dây chuyền gia công và Lò nung",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 15,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 162,
    họVàTên: "Lê Duy Hùng",
    mãNhânViên: "NV0659",
    bộPhận: "Tổ trưởng dây chuyền - Bộ phận dây chuyền gia công và Lò nung",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 10,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 163,
    họVàTên: "Phạm Thanh Hải",
    mãNhânViên: "NV0106",
    bộPhận: "Tổ trưởng - Phụ trách Đóng hộp DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 164,
    họVàTên: "Nguyễn Văn Duẩn",
    mãNhânViên: "NV0657",
    bộPhận: "Phó bộ phận - Phụ trách Dây chuyền gia công DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: 3,
    tháng11: null,
    tổng: 8,
  },
  {
    tt: 165,
    họVàTên: "Nguyễn Viết Linh",
    mãNhânViên: "NV1892",
    bộPhận: "Tổ trưởng bao gói - Bộ phận Mài đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 166,
    họVàTên: "Nguyễn Việt Anh",
    mãNhânViên: "NV2473",
    bộPhận: "Tổ trưởng bao gói - Bộ phận Mài đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 167,
    họVàTên: "Lê Thị Ánh",
    mãNhânViên: "NV5302",
    bộPhận: "Vệ sinh công nghiệp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 168,
    họVàTên: "Lê Ngọc Quỳnh",
    mãNhânViên: "NV4900",
    bộPhận: "VH lò nung xương dây chuyền 5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 9,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 9,
  },
  {
    tt: 169,
    họVàTên: "Trần Văn Hệ",
    mãNhânViên: "NV0623",
    bộPhận: "Tổ phó lò nung dây chuyền 5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 170,
    họVàTên: "Đặng Viết Xứng",
    mãNhânViên: "NV0769",
    bộPhận: "Phó bộ phận lò nung dây chuyền 5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 2,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 171,
    họVàTên: "Trần Thị Yến",
    mãNhânViên: "NV1867",
    bộPhận: "Kế toán tổng hợp - Phòng kế toán",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 172,
    họVàTên: "Nguyễn Văn Gia",
    mãNhânViên: "NV4896",
    bộPhận: "Công nhân VH mài cạnh - Bộ Phận mài",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 173,
    họVàTên: "Lê Như Hiệp",
    mãNhânViên: "NV4535",
    bộPhận: "Công nhân VH mài Nano - Bộ Phận mài",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 174,
    họVàTên: "Phạm Hồng Như",
    mãNhânViên: "NV0057",
    bộPhận: "CBKT Bộ phận công nghệ",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 10,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 175,
    họVàTên: "Bùi Khắc Toàn",
    mãNhânViên: "NV2085",
    bộPhận: "Công nhân bộ phận nghiền sấy phun",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 11,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 11,
  },
  {
    tt: 176,
    họVàTên: "Trịnh Xuân Mong",
    mãNhânViên: "NV2093",
    bộPhận: "Tổ phó nghiền sấy phun ca B",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 6,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 177,
    họVàTên: "Đặng Viết Định",
    mãNhânViên: "NV5639",
    bộPhận: "Công nhân bao gói ca A - phân xưởng sản xuất 1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 178,
    họVàTên: "Nguyễn Việt Anh",
    mãNhânViên: "NV2473",
    bộPhận: "Tổ trưởng bao gói - Bộ phận Mài đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 5,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 179,
    họVàTên: "Lê Đình Dũng",
    mãNhânViên: "NV5636",
    bộPhận: "Công nhân bao gói - Dây chuyền 5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 6,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 180,
    họVàTên: "Nguyễn Trọng Thức",
    mãNhânViên: "NV0231",
    bộPhận: "Công nhân VH máy mài mặt - Dây chuyền 5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 10,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 181,
    họVàTên: "Trịnh Văn Trọng",
    mãNhânViên: "NV5062",
    bộPhận: "Công nhân bao gói - Dây chuyền 5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 4,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 182,
    họVàTên: "Nguyễn Duy Toàn",
    mãNhânViên: "NV5594",
    bộPhận: "Công nhân bao gói - Dây chuyền 5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 4,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 183,
    họVàTên: "Nguyễn Xuân Hạnh",
    mãNhânViên: "NV2719",
    bộPhận: "Công nhân dây chuyền - Dây chuyền 6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 10,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 184,
    họVàTên: "Lê Văn Thành",
    mãNhânViên: "NV5585",
    bộPhận: "Công nhân bao gói - Dây chuyền 5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 4,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 185,
    họVàTên: "Nguyễn Lê Trang",
    mãNhânViên: "NV5485",
    bộPhận: "Công nhân lò nung bao gói - Dây chuyền 6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 4,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 186,
    họVàTên: "Nguyễn Sĩ Sáu",
    mãNhânViên: "NV5222",
    bộPhận: "Công nhân bao gói ca A - DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 4,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 187,
    họVàTên: "Lê Trọng Tấn",
    mãNhânViên: "NV3530",
    bộPhận: "Nhân viên lái máy - Tổ đội xe máy - Phòng khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: 13,
    tháng9: null,
    tháng10: null,
    tháng11: null,
    tổng: 13,
  },
  {
    tt: 188,
    họVàTên: "Lê Đình Văn",
    mãNhânViên: "NV5504",
    bộPhận: "CN sơ chế - Tổ PVXH - Phòng kế toán",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 189,
    họVàTên: "Nguyễn Thị Hiền",
    mãNhânViên: "NV0163",
    bộPhận: "NV phân loại - bộ phận thanh tra sản xuất",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 6,
    tháng10: null,
    tháng11: null,
    tổng: 6,
  },
  {
    tt: 190,
    họVàTên: "Trịnh Tuấn Linh",
    mãNhânViên: "NV1200",
    bộPhận: "CN vận hành máy in KTS",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 4,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 191,
    họVàTên: "Lê Duy Vĩnh",
    mãNhânViên: "NV3737",
    bộPhận: "CN vận hành mấy ép",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 192,
    họVàTên: "Hoàng Văn Hưng",
    mãNhânViên: "NV5660",
    bộPhận: "CN đóng hôp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 193,
    họVàTên: "Đào Văn Tính",
    mãNhânViên: "NV1007",
    bộPhận: "CN vânh hành bể mài",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 2,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 194,
    họVàTên: "Nguyễn Hoàng Kỷ",
    mãNhânViên: "NV2781",
    bộPhận: "CN vânh hành bể mài",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 2,
    tháng10: null,
    tháng11: null,
    tổng: 2,
  },
  {
    tt: 195,
    họVàTên: "Phạm Khắc Thành",
    mãNhânViên: "NV5136",
    bộPhận: "CN vận hành bể nước ca A - DC5 - Phân xưởng 2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 196,
    họVàTên: "Nguyễn Duy Toàn",
    mãNhânViên: "NV5594",
    bộPhận: "CN bao gói ca A - DC5 - Phân xưởng 2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 4,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 197,
    họVàTên: "Lê Công Dũng",
    mãNhânViên: "NV3688",
    bộPhận: "CN VH mài măth ca A - DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 4,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 198,
    họVàTên: "Phạm Văn Chiến",
    mãNhânViên: "NV0617",
    bộPhận: "Tổ trưởng lò nung - đóng hộp ca B - DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 199,
    họVàTên: "Trương Duy Long",
    mãNhânViên: "NV2036",
    bộPhận: "Lái xe nâng nội bộ DC5 - Phân xưởng 2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 4,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 200,
    họVàTên: "Trịnh Xuân Chung",
    mãNhânViên: "NV5589",
    bộPhận: "CN bao gói ca B - DC5 - Phân xưởng 2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 4,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 201,
    họVàTên: "Lê Xuân Tùng",
    mãNhânViên: "NV3723",
    bộPhận: "CN bao gói ca B - DC5 - Phân xưởng 2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 4,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 202,
    họVàTên: "Phạm Đình Tùng",
    mãNhânViên: "NV5592",
    bộPhận: "CN bao gói ca B - DC5 - Phân xưởng 3",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 4,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 203,
    họVàTên: "Lê Đồng Việt",
    mãNhânViên: "NV5574",
    bộPhận: "Công nhân đóng bao DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 4,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 204,
    họVàTên: "Trịnh Văn Trọng",
    mãNhânViên: "NV5062",
    bộPhận: "Công nhân đóng bao DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 4,
    tháng10: null,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 205,
    họVàTên: "Lê Đình Huy",
    mãNhânViên: "NV3835",
    bộPhận: "VH máy in KTS DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 10,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 206,
    họVàTên: "Lê Văn Lực",
    mãNhânViên: "NV0537",
    bộPhận: "VH nạp liệu",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 10,
    tháng10: null,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 207,
    họVàTên: "Lê Đồng Việt",
    mãNhânViên: "NV5574",
    bộPhận: "CN đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 208,
    họVàTên: "Nguyễn Hữu Hiếu",
    mãNhânViên: "NV1032",
    bộPhận: "Tổ đội xe máy",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 209,
    họVàTên: "Lê Xuân Toán",
    mãNhânViên: "NV0375",
    bộPhận: "Tổ đội xe máy",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 210,
    họVàTên: "Nguyễn Xuân Thuỷ",
    mãNhânViên: "NV0519",
    bộPhận: "Tổ đội xe máy",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 15,
    tháng10: null,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 211,
    họVàTên: "Lê Đức Kiệm",
    mãNhânViên: "NV0716",
    bộPhận: "Tổ đội xe máy",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 212,
    họVàTên: "Hà Trường Giang",
    mãNhânViên: "NV5532",
    bộPhận: "BP khai thác mỏ",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 8,
    tháng10: null,
    tháng11: null,
    tổng: 8,
  },
  {
    tt: 213,
    họVàTên: "Trương Quốc Hoàn",
    mãNhânViên: "NV1229",
    bộPhận: "Tổ đội xe máy",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: 5,
    tháng10: null,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 214,
    họVàTên: "Trần Đức Đảm",
    mãNhânViên: "NV0412",
    bộPhận: "NV bảo vệ - Phòng tổ chức",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 215,
    họVàTên: "Trịnh Văn Hoà",
    mãNhânViên: "NV0417",
    bộPhận: "Thủ kho - Phòng kế Toán",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 216,
    họVàTên: "Nguyễn Bá Quân",
    mãNhânViên: "NV0986",
    bộPhận: "NV cơ điện - Phòng kỹ thuật",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 18,
    tháng11: null,
    tổng: 18,
  },
  {
    tt: 217,
    họVàTên: "Nguyễn Văn Học",
    mãNhânViên: "NV0119",
    bộPhận: "NT cơ điện - Phòng kỹ thuật",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 18,
    tháng11: null,
    tổng: 18,
  },
  {
    tt: 218,
    họVàTên: "Vũ Xuân Lân",
    mãNhânViên: "NV0090",
    bộPhận: "PP kỹ thuật",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 10,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 219,
    họVàTên: "Hồ Xuân Tùng",
    mãNhânViên: "NV0451",
    bộPhận: "TP kỹ thuật",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 10,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 220,
    họVàTên: "Nguyễn Đăng Điệp",
    mãNhânViên: "NV2576",
    bộPhận: "CN VH sấy DC1",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 221,
    họVàTên: "Đào Đình Quyết",
    mãNhânViên: "NV5637",
    bộPhận: "Lái xe nâng ca B",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 4,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 222,
    họVàTên: "Cao Thế Vinh",
    mãNhânViên: "NV5052",
    bộPhận: "CN VH mài",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 20,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 223,
    họVàTên: "Nguyễn Văn Cường",
    mãNhânViên: "NV5456",
    bộPhận: "CN VH mài",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 15,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 224,
    họVàTên: "Lê Văn Nam",
    mãNhânViên: "NV3949",
    bộPhận: "CN VH mài",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 15,
    tháng11: null,
    tổng: 15,
  },
  {
    tt: 225,
    họVàTên: "Nguyễn Quốc Huy",
    mãNhânViên: "NV5176",
    bộPhận: "CN cơ điện HC",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 7,
    tháng11: null,
    tổng: 7,
  },
  {
    tt: 226,
    họVàTên: "Đỗ Viết Trang",
    mãNhânViên: "NV3135",
    bộPhận: "CN nạp liệu",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 21,
    tháng11: null,
    tổng: 21,
  },
  {
    tt: 227,
    họVàTên: "Nguyễn Đăng Hùng",
    mãNhânViên: "NV5640",
    bộPhận: "Hoàn thiện palet",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 20,
    tháng11: null,
    tổng: 20,
  },
  {
    tt: 228,
    họVàTên: "Nguyễn Trọng Tiến",
    mãNhânViên: "NV0243",
    bộPhận: "Lái xe nâng nội bộ DC5 - Phân xưởng 2",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 229,
    họVàTên: "Lê Xuân Bắc",
    mãNhânViên: "NV0575",
    bộPhận: "TT bp đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 10,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 230,
    họVàTên: "Phạm Duy Thiết",
    mãNhânViên: "NV0651",
    bộPhận: "CN vh máy ép",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 231,
    họVàTên: "Lê Đình Lâm",
    mãNhânViên: "NV2148",
    bộPhận: "PBP Dây chuyền 5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 232,
    họVàTên: "Nguyễn Thương Huyền",
    mãNhânViên: "NV0606",
    bộPhận: "CN VH tráng engobe DC6",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 233,
    họVàTên: "Lê Đồng Việt",
    mãNhânViên: "NV5574",
    bộPhận: "TT lò nung đóng hộp DC5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 3,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 234,
    họVàTên: "Đỗ Ngọc Đức",
    mãNhânViên: "NV4465",
    bộPhận: "CN đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 3,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 235,
    họVàTên: "Ngô Công Tám",
    mãNhânViên: "NV5496",
    bộPhận: "CN đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 3,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 236,
    họVàTên: "Lê Văn Kiên",
    mãNhânViên: "NV4424",
    bộPhận: "CN đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 3,
    tháng11: null,
    tổng: 3,
  },
  {
    tt: 237,
    họVàTên: "Nguyễn Viết Linh",
    mãNhânViên: "NV1892",
    bộPhận: "CN đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 238,
    họVàTên: "Lê Văn Linh",
    mãNhânViên: "NV0424",
    bộPhận: "TT đóng hộp dc5",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 239,
    họVàTên: "Lê Duy Nguyên",
    mãNhânViên: "NV3529",
    bộPhận: "Tổ phó nghiền men",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 240,
    họVàTên: "Nguyễn Công Hoà",
    mãNhânViên: "NV5710",
    bộPhận: "CN VH nghiền men",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 4,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 241,
    họVàTên: "Trịnh Văn Trọng",
    mãNhânViên: "NV5062",
    bộPhận: "CN đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 4,
    tháng11: null,
    tổng: 4,
  },
  {
    tt: 242,
    họVàTên: "Lê Văn Khoa",
    mãNhânViên: "NV2404",
    bộPhận: "CN đóng hộp",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 5,
    tháng11: null,
    tổng: 5,
  },
  {
    tt: 243,
    họVàTên: "Nguyễn Văn Hải",
    mãNhânViên: "NV2509",
    bộPhận: "NV lái xe - Phòng khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 10,
    tháng11: null,
    tổng: 10,
  },
  {
    tt: 244,
    họVàTên: "Nguyễn Đình Tứ",
    mãNhânViên: "NV5779",
    bộPhận: "NV lái máy xúc đào - Phòng khai thác",
    tháng2: null,
    tháng3: null,
    tháng4: null,
    tháng5: null,
    tháng6: null,
    tháng7: null,
    tháng8: null,
    tháng9: null,
    tháng10: 11,
    tháng11: null,
    tổng: 11,
  },
];